/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi_apotek;
import javax.swing.JOptionPane;// membuat pesan dialog
import java.sql.*;// untuk menampilkan data dara perintah query





public class form_data_obat extends javax.swing.JFrame {
    
    String JudulKolom[]={"Kode Obat","Nama Obat","Jenis Obat","Satuan","Stok Obat","Harga Beli Obat","Harga Jual Obat"};
    String sqlData_Obat="SELECT*FROM dataobat";
    int lebarKolom[]={100,300,100,60,200,60};
    
    /**
     * Creates new form form_data_obat
     */
    public form_data_obat() {
        initComponents();
        this.setLocationRelativeTo(null);
// untuk memposisikan form ditengah layar
new ConfigDB().tampilTabel(JudulKolom, sqlData_Obat, JTable_Obat);
new ConfigDB().aturLebarKolom(JTable_Obat, lebarKolom);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Txt_Nama = new javax.swing.JTextField();
        Txt_Stok_Obat = new javax.swing.JTextField();
        Txt_Harga = new javax.swing.JTextField();
        Txt_Harga_Jual = new javax.swing.JTextField();
        Cbb_Jenis_Obat = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Txt_kode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Txt_Satuan = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTable_Obat = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        PENCARIAN = new javax.swing.JTextField();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("DATA OBAT");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("ZAINI MEDIKA FARMA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 153, 0));

        jLabel3.setText("Nama Obat");

        jLabel4.setText("Jenis Obat");

        jLabel5.setText("Satuan");

        jLabel6.setText("Stok Obat");

        jLabel7.setText("Harga Beli Obat");

        jLabel8.setText("Harga Jual Obat");

        Txt_Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NamaActionPerformed(evt);
            }
        });

        Cbb_Jenis_Obat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("HAPUS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("UBAH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("SIMPAN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Txt_kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_kodeActionPerformed(evt);
            }
        });

        jLabel2.setText("Kode Obat");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Txt_Harga_Jual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Harga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Nama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_kode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Txt_Satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cbb_Jenis_Obat, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Stok_Obat, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cbb_Jenis_Obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_Harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Stok_Obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_Harga_Jual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel7)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel8)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));

        JTable_Obat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTable_Obat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_ObatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTable_Obat);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        PENCARIAN.setText("PENCARIAN");
        PENCARIAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PENCARIANActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PENCARIAN, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(PENCARIAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_kodeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
if (Txt_kode.getText().isEmpty()){
JOptionPane.showMessageDialog(null,"kode obat belum diisi");
Txt_kode.requestFocus();
} else 
if (Txt_Nama.getText().isEmpty()){
JOptionPane.showMessageDialog(null,"nama obat belum diisi");
Txt_Nama.requestFocus();
} else
if (Txt_Stok_Obat.getText().isEmpty()){
JOptionPane.showMessageDialog(null,"stok obat belum diisi");
Txt_Stok_Obat.requestFocus();
} else
if (String.valueOf(Cbb_Jenis_Obat.getSelectedItem())==".: Pilih Judul :."){
JOptionPane.showMessageDialog(null,"Genre film belum diisi");
Cbb_Jenis_Obat.requestFocus(); 
} else
    if (Txt_Harga.getText().isEmpty()){
JOptionPane.showMessageDialog(null,"harga beli belum diisi");
Txt_Harga.requestFocus();
} else
        if (Txt_Harga_Jual.getText().isEmpty()){
JOptionPane.showMessageDialog(null,"harga jual belum diisi");
Txt_Harga_Jual.requestFocus();
} else
if (Txt_Satuan.getText().isEmpty()){
JOptionPane.showMessageDialog(null,"satuan belum diisi");
Txt_Satuan.requestFocus();
Statement st= new ConfigDB().koneksi.createStatement();
ResultSet rs = st.executeQuery("SELECT*FROM film WHERE Kode Obat ='"+Txt_kode.getText()+"'");
if (rs.next()){
Txt_Nama.setText(rs.getString("judul"));
Txt_Stok_Obat.setText(rs.getString("judul"));
Cbb_Jenis_Obat.setSelectedItem(String
.valueOf(rs.getString("genre")));
Txt_Harga.setText(rs.getString("tahun"));
Txt_Harga_Jual.setText(rs.getString("asal"));
Txt_Satuan.setText(rs.getString("stok"));
}
 

}else{
String SQL="INSERT INTO obat VALUES('"+Txt_kode.getText()+"','"+Txt_Nama.getText()+"','"+Txt_Stok_Obat.getText()+"','"+Txt_Harga.getText()+"','"+
String.valueOf(Cbb_Jenis_Obat.getSelectedItem())+"','"+Txt_Harga_Jual.getText()+"','"+Txt_Satuan.getText()+"')";
new ConfigDB().simpanData(SQL);
new ConfigDB().tampilTabel(JudulKolom, sqlData_Obat, JTable_Obat);
new ConfigDB().aturLebarKolom(JTable_Obat, lebarKolom);
}
} catch (Exception e) {
}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
if (
(Txt_kode.getText().isEmpty()) && (Txt_Nama.getText().isEmpty()) &&
(Txt_Stok_Obat.getText().isEmpty()) && (Txt_Harga.getText().isEmpty()) &&
(Txt_Harga_Jual.getText().isEmpty()) && (Txt_Satuan.getText().isEmpty()) &&
(String.valueOf(Cbb_Jenis_Obat.getSelectedItem())==".: Pilih Judul :.")                         
)
{
JOptionPane.showMessageDialog(null,"Silahkan  Pilih  Data  dulu  untuk  proses Ubah");
JTable_Obat.requestFocus();
} else
{
String SQL="UPDATE Obat SET Nama_Obat ='"+Txt_Nama.getText()+"', Jenis_Obat='"+String.valueOf(Cbb_Jenis_Obat.getSelectedItem()) 
+"', Stok_Obat='"+Txt_Stok_Obat.getText()+"', Harga='"+Txt_Harga.getText()+"', Harga_Jual='"+Txt_Harga_Jual.getText()+"' WHERE Satuan='"+Txt_Satuan.getText()+"'";
new ConfigDB().ubahData(SQL);
new ConfigDB().tampilTabel(JudulKolom, sqlData_Obat, JTable_Obat);
new ConfigDB().aturLebarKolom(JTable_Obat, lebarKolom);
}       
} catch (Exception
e) 
{
System.out.print(e.toString());
}
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void Txt_NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NamaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
if (
(Txt_kode.getText().isEmpty()) && (Txt_Nama.getText().isEmpty()) &&
(Txt_Stok_Obat.getText().isEmpty()) && (Txt_Harga.getText().isEmpty()) &&
(Txt_Harga_Jual.getText().isEmpty()) && (Txt_Harga_Jual.getText().isEmpty()) &&
(String.valueOf(Cbb_Jenis_Obat.getSelectedItem())==".: Pilih Jenis :.")                         
)
{
JOptionPane.showMessageDialog(null,"Silahkan  Pilih  Data  dulu  untuk  proses Hapus");
JTable_Obat.requestFocus();
} else
{
String SQL="DELETE FROM film WHERE Kode_Obat='"+Txt_kode.getText()+"'";
new ConfigDB().hapusData(SQL);
new ConfigDB().tampilTabel(JudulKolom, sqlData_Obat, JTable_Obat);
new ConfigDB().aturLebarKolom(JTable_Obat, lebarKolom);
}
} catch (Exception e) 
{
System.out.print(e.toString());
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
Txt_kode.setText(null);
Txt_Nama.setText(null);
Txt_Stok_Obat.setText(null);
Txt_Harga.setText(null);
Txt_Harga_Jual.setText(null);
Txt_Satuan.setText(null);
Cbb_Jenis_Obat.setSelectedItem(String.valueOf(".: Pilih Jenis :."));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new ConfigDB().tampilTabel(JudulKolom, sqlData_Obat, JTable_Obat);
        new ConfigDB().aturLebarKolom(JTable_Obat, lebarKolom);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void JTable_ObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_ObatMouseClicked
        // TODO add your handling code here:
        try {
int baris = JTable_Obat.getSelectedRow();
Txt_kode.setText(String.valueOf(JTable_Obat.getValueAt(baris,0)));
Txt_Nama.setText(String.valueOf(JTable_Obat.getValueAt(baris,1)));
Cbb_Jenis_Obat.setSelectedItem(String.valueOf(JTable_Obat.getValueAt(baris,2)));
Txt_Stok_Obat.setText(String.valueOf(JTable_Obat.getValueAt(baris,3)));
Txt_Harga.setText(String.valueOf(JTable_Obat.getValueAt(baris,4)));
Txt_Harga_Jual.setText(String.valueOf(JTable_Obat.getValueAt(baris,5)));
Txt_Satuan.setText(String.valueOf(JTable_Obat.getValueAt(baris,6)));
} catch (Exception e) {
    
System.out.print(e.toString());
}

    }//GEN-LAST:event_JTable_ObatMouseClicked

    private void PENCARIANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PENCARIANActionPerformed
        // TODO add your handling code here:
        try {
String SQL="SELECT*FROM DataObat WHERE judul like '%"+PENCARIAN.getText()+"%'";
new ConfigDB().cariData(JudulKolom, SQL, JTable_Obat); 
} catch (Exception e) {
System.out.print(e.toString());
}
    }//GEN-LAST:event_PENCARIANActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_data_obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_data_obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_data_obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_data_obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_data_obat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cbb_Jenis_Obat;
    private javax.swing.JTable JTable_Obat;
    private javax.swing.JTextField PENCARIAN;
    private javax.swing.JTextField Txt_Harga;
    private javax.swing.JTextField Txt_Harga_Jual;
    private javax.swing.JTextField Txt_Nama;
    private javax.swing.JTextField Txt_Satuan;
    private javax.swing.JTextField Txt_Stok_Obat;
    private javax.swing.JTextField Txt_kode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
